# Generated by Django 4.2.26 on 2026-02-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_bodega_estado_alter_categoria_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='compania',
            field=models.CharField(choices=[('ECL', 'ECL'), ('INTERCARGO', 'Intercargo'), ('ECOLOGISTICS', 'Ecologistics'), ('TLC', 'TLC'), ('TLSS', 'TLSS')], default='ECL', max_length=20, verbose_name='Compañía'),
        ),
    ]
