# Generated by Django 4.2.26 on 2026-02-19 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_elemento_capacidad_elemento_caracteristica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elemento',
            name='nombre',
        ),
    ]
