# Generated by Django 4.2.26 on 2026-03-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_alter_movimientoinventario_tipo_movimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('Asignacion', 'Asignación'), ('Reasignacion', 'Reasignación'), ('Devolucion', 'Devolución'), ('Baja', 'Baja')], max_length=30, verbose_name='Tipo de Movimiento'),
        ),
    ]
