# Generated by Django 4.2.26 on 2026-03-31 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_perfilusuario_puede_autorizar'),
        ('inventario', '0017_movimientoinventario_usuario_autoriza'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='condicion',
            field=models.CharField(choices=[('Propio', 'Propio'), ('Rentado', 'En Renta')], default='Propio', max_length=20, verbose_name='Condición del Equipo'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='periodicidad_pago',
            field=models.CharField(blank=True, choices=[('N/A', 'No Aplica'), ('Mensual', 'Mensual'), ('Bimestral', 'Bimestral'), ('Anual', 'Anual')], default='N/A', max_length=20, null=True, verbose_name='Periodicidad de Pago'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='usuario_autoriza',
            field=models.ForeignKey(blank=True, help_text='Usuario que autoriza el movimiento', limit_choices_to={'puede_autorizar': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_autorizados', to='usuarios.perfilusuario', verbose_name='Autorizado por'),
        ),
    ]
