# Generated by Django 4.2.26 on 2026-04-07 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_elemento_condicion_elemento_periodicidad_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='elemento_padre',
            field=models.ForeignKey(blank=True, help_text='Seleccione el software Máster si esta es una sub-licencia o usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_elementos', to='inventario.elemento', verbose_name='Cuenta principal (Máster)'),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='condicion',
            field=models.CharField(choices=[('Propio', 'Propio'), ('Rentado', 'En Renta'), ('Suscripcion', 'Suscripcion / Software')], default='Propio', max_length=20, verbose_name='Condición del Equipo'),
        ),
    ]
