# Generated by Django 4.2.26 on 2026-04-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_elemento_elemento_padre_alter_elemento_condicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='cuenta_asociada',
            field=models.CharField(blank=True, help_text='Correo electrónico o usuario con el que se ingresa al software', max_length=150, null=True, verbose_name='Cuenta / Correo Asociado'),
        ),
    ]
