# Generated by Django 4.2.26 on 2026-05-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_alter_movimientoinventario_estado_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
    ]
