# Generated by Django 4.2.26 on 2026-05-26 21:50

import apps.inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0025_elemento_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='firma_autoriza',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='firma_elabora',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='firma_recibe',
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='documento_soporte',
            field=models.FileField(blank=True, null=True, upload_to=apps.inventario.models.ruta_documento_soporte, validators=[apps.inventario.models.validar_peso_archivo], verbose_name='Documento Soporte'),
        ),
    ]
