# Generated by Django 4.2.26 on 2026-01-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='fecha_asignacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Asignación'),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='id',
            field=models.CharField(help_text='Identificador único del elemento en el inventario()', max_length=20, primary_key=True, serialize=False, verbose_name='ID del Elemento'),
        ),
    ]
