# Generated by Django 4.2.26 on 2026-02-03 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfilusuario_tipo_usuario'),
        ('inventario', '0003_alter_elemento_usuario_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Asignado', 'Asignado'), ('Mantenimiento', 'Mantenimiento'), ('Averiado', 'Averiado'), ('Baja', 'Baja')], default='Activo', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='detallemovimiento',
            name='usuario_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elementos_asignados_detalle', to='usuarios.perfilusuario', verbose_name='Usuario Actual'),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='usuario_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elementos_asignados', to='usuarios.perfilusuario', verbose_name='Usuario Actual'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='usuario_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='usuarios.perfilusuario', verbose_name='Usuario Destino'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='usuario_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='usuarios.perfilusuario', verbose_name='Usuario Origen'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='usuario_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_registrados', to='usuarios.perfilusuario', verbose_name='Usuario que Registra'),
        ),
    ]
