# Generated by Django 4.2.26 on 2026-02-16 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_bodega_es_bodega_principal_nombreelemento_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elemento',
            name='sn',
        ),
    ]
