# Generated by Django 4.2.26 on 2026-02-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_remove_elemento_sn'),
    ]

    operations = [
        migrations.AddField(
            model_name='nombreelemento',
            name='requiere_imei2',
            field=models.BooleanField(default=False, help_text='Marca si este elemento requiere IMEI secundario (ej: Celulares dual SIM)', verbose_name='Requiere IMEI 2'),
        ),
        migrations.AddField(
            model_name='nombreelemento',
            name='requiere_serial',
            field=models.BooleanField(default=True, help_text='Marca si este elemento requiere número de serie', verbose_name='Requiere serial'),
        ),
        migrations.AlterField(
            model_name='nombreelemento',
            name='requiere_color',
            field=models.BooleanField(default=False, help_text='Marca si este elemento requiere especificar color', verbose_name='Requiere Color'),
        ),
        migrations.AlterField(
            model_name='nombreelemento',
            name='requiere_imei',
            field=models.BooleanField(default=False, help_text='Marca si este elemento requiere IMEI', verbose_name='Requiere IMEI'),
        ),
    ]
