# Generated by Django 4.2.26 on 2026-02-19 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_remove_elemento_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='nombre_elemento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='elementos_relacionados', to='inventario.nombreelemento', verbose_name='Nombre del Elemento'),
            preserve_default=False,
        ),
    ]
