# Generated by Django 4.2.26 on 2026-03-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_remove_movimientoinventario_bodega_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('Asignacion', 'Asignación'), ('Reasignacion', 'Reasignación'), ('Devolucion', 'Devolución'), ('Entrada', 'Entrada'), ('Baja', 'Baja')], max_length=30, verbose_name='Tipo de Movimiento'),
        ),
    ]
