# Generated by Django 4.2.26 on 2026-03-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_alter_movimientoinventario_tipo_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='firma_autoriza',
            field=models.ImageField(blank=True, null=True, upload_to='firmas_movimientos/', verbose_name='Firma Autoriza'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='firma_elabora',
            field=models.ImageField(blank=True, null=True, upload_to='firmas_movimientos/', verbose_name='Firma Elabora'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='firma_recibe',
            field=models.ImageField(blank=True, null=True, upload_to='firmas_movimientos/', verbose_name='Firma Recibe'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='firmado_completamente',
            field=models.BooleanField(default=False, verbose_name='Firmado Completamente'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('Asignacion', 'Asignación'), ('Reasignacion', 'Reasignación'), ('Devolucion', 'Devolución'), ('Mantenimiento', 'Mantenimiento'), ('Baja', 'Baja')], max_length=30, verbose_name='Tipo de Movimiento'),
        ),
    ]
