# Generated by Django 4.2.26 on 2026-02-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilusuario_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('usuario_final', 'Usuario Final'), ('tecnico', 'Técnico'), ('bodega', 'Bodega')], default='usuario_final', max_length=20, verbose_name='Tipo de Usuario'),
        ),
    ]
