# Generated by Django 4.2.26 on 2026-03-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_perfilusuario_datos_ecl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='puede_autorizar',
            field=models.BooleanField(default=False, help_text='Marca si este usuario puede autorizar movimientos de inentario', verbose_name='Puede Autorizar Movimientos'),
        ),
    ]
