# Generated by Django 5.2.14 on 2026-07-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_perfilusuario_accesos_software'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='cargo_contrato',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo del contrato'),
        ),
    ]
