# Generated by Django 4.2.26 on 2026-08-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_perfilusuario_cargo_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='uuid_gh',
            field=models.UUIDField(blank=True, db_index=True, help_text='Identidad inmutable (sub) del usuario en Gestión Humana (IdP)', null=True, unique=True),
        ),
    ]
