# Generated by Django 4.2.26 on 2026-02-25 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfilusuario_tipo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='datos_ecl',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='gestion_humana_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID del usuario en Gestión Humana (sistema maestro)', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ultima_sincronizacion_gh',
            field=models.DateTimeField(blank=True, help_text='Última sincronización con Gestión Humana', null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuarios.rol', verbose_name='Rol'),
        ),
    ]
