# Generated by Django 4.2.26 on 2026-08-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '009_perfil_usuario_uuid_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='ciudad',
            field=models.CharField(blank=True, choices=[('Bogotá', 'Bogotá'), ('Buenaventura', 'Buenaventura'), ('Cali', 'Cali'), ('Cartagena', 'Cartagena'), ('Cúcuta', 'Cúcuta'), ('Medellín', 'Medellín'), ('Yopal', 'Yopal')], max_length=50, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='uuid_gh',
            field=models.UUIDField(blank=True, db_index=True, help_text='Identidad inmutable (sub) del usuario en Gestión Humana (IdP)', null=True, unique=True),
        ),
    ]
