# Generated by Django 4.2.26 on 2026-07-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0030_alter_plataformasoftware_options_delete_perfil'),
        ('usuarios', '0005_perfilusuario_puede_autorizar'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='accesos_software',
            field=models.ManyToManyField(blank=True, to='inventario.plataformasoftware', verbose_name='Software Asignado'),
        ),
    ]
