# Generated by Django 4.2.26 on 2026-01-20 21:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_bodega', models.CharField(choices=[('Principal Bogotá', 'Principal Bogotá'), ('Agencia Buenaventura', 'Agencia Buenaventura'), ('Agencia Cartagena', 'Agencia Cartagena')], max_length=200, unique=True, verbose_name='Nombre de la Bodega')),
                ('ubicacion', models.CharField(choices=[('Bogotá', 'Bogotá'), ('Buenaventura', 'Buenaventura'), ('Cartagena', 'Cartagena')], max_length=200, verbose_name='Ubicación')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado')),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bodegas_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable')),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'db_table': 'bodegas',
                'ordering': ['nombre_bodega'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('Asignacion', 'Asignación'), ('Reasignacion', 'Reasignación'), ('Devolucion', 'Devolución'), ('Entrada', 'Entrada'), ('Salida', 'Salida'), ('Baja', 'Baja')], max_length=30, verbose_name='Tipo de Movimiento')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Movimiento')),
                ('hora_movimiento', models.TimeField(auto_now_add=True, verbose_name='Hora del movimiento')),
                ('estado_movimiento', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Realizado', 'Realizado'), ('Cancelado', 'Cancelado')], default='Realizado', max_length=20, verbose_name='Estado del Movimiento')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones Generales')),
                ('documento_soporte', models.FileField(blank=True, null=True, upload_to='documentos_movimientos/', verbose_name='Documento Soporte')),
                ('bodega_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='inventario.bodega', verbose_name='Bodega Destino')),
                ('bodega_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='inventario.bodega', verbose_name='Bodega Origen')),
                ('usuario_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Destino')),
                ('usuario_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Origen')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registra')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'movimientos_inventario',
                'ordering': ['-fecha_movimiento', '-hora_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Elemento')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial')),
                ('imei', models.CharField(blank=True, max_length=50, null=True, verbose_name='IMEI')),
                ('sn', models.CharField(blank=True, max_length=100, null=True, verbose_name='SN')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('factura', models.FileField(blank=True, null=True, upload_to='documentos_elementos/facturas/', verbose_name='Factura')),
                ('documento_adicional', models.FileField(blank=True, null=True, upload_to='documentos_elementos/adicionales/', verbose_name='Documento Adicional')),
                ('estado', models.CharField(blank=True, choices=[('Disponible', 'Disponible'), ('Asignado', 'Asignado'), ('Mantenimiento', 'Mantenimiento'), ('Baja', 'Baja')], default='Disponible', max_length=20, null=True, verbose_name='Estado')),
                ('fecha_compra', models.DateField(verbose_name='Fecha de Compra')),
                ('garantia_hasta', models.DateField(verbose_name='Garantía Hasta')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('bodega_actual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elementos', to='inventario.bodega', verbose_name='Bodega Actual')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elementos', to='inventario.categoria', verbose_name='categoria')),
                ('ultimo_movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elementos_ultimo_mov', to='inventario.movimientoinventario', verbose_name='Último Movimiento')),
                ('usuario_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elementos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Actual')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elementos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registro')),
            ],
            options={
                'verbose_name': 'Elemento',
                'verbose_name_plural': 'Elementos',
                'db_table': 'elementos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='DetalleMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('estado_elemento_antes', models.CharField(blank=True, choices=[('Óptimo', 'Óptimo'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], max_length=20, null=True, verbose_name='Estado Antes')),
                ('estado_elemento_despues', models.CharField(blank=True, choices=[('Óptimo', 'Óptimo'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], max_length=20, null=True, verbose_name='Estado Después')),
                ('observaciones_elemento', models.TextField(blank=True, null=True, verbose_name='Observaciones del Elemento')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_movimiento', to='inventario.elemento', verbose_name='Elemento')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.movimientoinventario', verbose_name='Movimiento')),
                ('usuario_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elementos_asignados_detalle', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Actual')),
            ],
            options={
                'verbose_name': 'Detalle de movimiento',
                'verbose_name_plural': 'Detalles de Movimiento',
                'db_table': 'detalle_movimiento',
                'ordering': ['movimiento', 'elemento'],
                'unique_together': {('movimiento', 'elemento')},
            },
        ),
    ]
