# Generated by Django 4.2.26 on 2026-01-30 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilusuario_estado'),
        ('inventario', '0002_elemento_fecha_asignacion_alter_elemento_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='usuario_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elementos_registrados', to='usuarios.perfilusuario', verbose_name='Usuario que registro'),
        ),
    ]
