# Generated by Django 4.2.26 on 2026-02-04 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_elemento_compania'),
    ]

    operations = [
        migrations.CreateModel(
            name='NombreElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Elemento')),
                ('requiere_imei', models.BooleanField(default=False, verbose_name='Requiere IMEI')),
                ('requiere_color', models.BooleanField(default=False, verbose_name='Requiere Color')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombres_elementos', to='inventario.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Nombre de Elemento',
                'verbose_name_plural': 'Nombres de Elementos',
                'db_table': 'nombres_elementos',
                'ordering': ['categoria', 'nombre'],
                'unique_together': {('categoria', 'nombre')},
            },
        ),
    ]
