# Generated by Django 4.2.26 on 2026-02-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_nombreelemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='es_bodega_principal',
            field=models.BooleanField(default=False, help_text='Marca si esta es la bodega principal con acceso a todas las demás bodegas', verbose_name='Es Bodega Principal'),
        ),
        migrations.AddField(
            model_name='nombreelemento',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
