# Generated by Django 4.2.26 on 2026-04-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_elemento_cuenta_asociada'),
    ]

    operations = [
        migrations.AddField(
            model_name='nombreelemento',
            name='requiere_correo',
            field=models.BooleanField(default=False, verbose_name='Requiere Correo Electrónico'),
        ),
    ]
