# Generated by Django 4.2.26 on 2026-05-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_rename_firmado_completamente_movimientoinventario_es_firmado_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='estado_movimiento',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Realizado', 'Realizado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20, verbose_name='Estado del Movimiento'),
        ),
    ]
