# Generated by Django 4.2.26 on 2026-06-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0027_movimientoinventario_firma_autoriza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='estado_movimiento',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Realizado', 'Realizado'), ('Cancelado', 'Cancelado'), ('Anulado', 'Anulado')], default='Pendiente', max_length=20, verbose_name='Estado del Movimiento'),
        ),
    ]
