# Generated by Django 4.2.26 on 2026-07-27 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0029_plataformasoftware_rol_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plataformasoftware',
            options={'verbose_name': 'Plataforma de Software', 'verbose_name_plural': 'Plataformas de Software'},
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
