# Generated by Django 4.2.26 on 2026-01-20 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ejecucion', models.DateField(verbose_name='Fecha de Ejecución')),
                ('tipo_mantenimiento', models.CharField(choices=[('Preventivo', 'Preventivo'), ('Correctivo', 'Correctivo'), ('Actualizacion', 'Actualización')], max_length=20, verbose_name='Tipo de Mantenimiento')),
                ('seguimiento_claves', models.TextField(blank=True, null=True, verbose_name='Seguimiento de Claves')),
                ('informe_equipo', models.TextField(blank=True, null=True, verbose_name='Informe del Equipo')),
                ('informe_usuario', models.TextField(blank=True, null=True, verbose_name='Informe del Usuario')),
                ('informe_fecha', models.DateField(blank=True, null=True, verbose_name='Fecha del Informe')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='inventario.elemento', verbose_name='Elemento')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsable')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'db_table': 'mantenimientos',
                'ordering': ['-fecha_ejecucion'],
            },
        ),
    ]
