# Generated by Django 4.2.26 on 2026-02-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_nombreelemento_requiere_imei2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='capacidad',
            field=models.CharField(blank=True, help_text='Ej:500GB, 1TB, 2 toneladas', max_length=50, null=True, verbose_name='Capacidad'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='caracteristica',
            field=models.CharField(blank=True, help_text='Ej:Caracteristica especial del elemento', max_length=200, null=True, verbose_name='Caracteristica'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='imei_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IMEI 2'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='mac',
            field=models.CharField(blank=True, help_text='Formato 12 digitos xx.xx.xx.xx.xx.xx', max_length=17, null=True, verbose_name='Dirección MAC'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='numero',
            field=models.CharField(blank=True, help_text='Ej:Claro, Movistar', max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='operador',
            field=models.CharField(blank=True, help_text='Ej:Claro, Movistar', max_length=50, null=True, verbose_name='Operador'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='puertos',
            field=models.CharField(blank=True, help_text='Ej:2xUSB-A, 1xHDMI, 4xRJ45', max_length=200, null=True, verbose_name='Puertos'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='tipo',
            field=models.CharField(blank=True, help_text='Ej:SSD, HDD, Inalámbrico', max_length=50, null=True, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='nombreelemento',
            name='requiere_capacidad',
            field=models.BooleanField(default=False, help_text='Ej: 5000Gb, 1TB, 2 tolenadas(almacenamiento o peso)', verbose_name='Requiere Capacidad'),
        ),
        migrations.AddField(
            model_name='nombreelemento',
            name='requiere_caracteristica',
            field=models.BooleanField(default=False, help_text='Caracteristica especial del elemento', verbose_name='Requiere Caracteristica'),
        ),
        migrations.AddField(
            model_name='nombreelemento',
            name='requiere_mac',
            field=models.BooleanField(default=False, help_text='Descripción adicional del elemento', verbose_name='Requiere MAC'),
        ),
        migrations.AddField(
            model_name='nombreelemento',
            name='requiere_marca',
            field=models.BooleanField(default=True, help_text='Ej: Samsung, HP , Dell', verbose_name='Requiere Marca'),
        ),
        migrations.AddField(
            model_name='nombreelemento',
            name='requiere_modelo',
            field=models.BooleanField(default=True, help_text='Ej: Galaxy s21, Probook 450', verbose_name='Requiere Moelo'),
        ),
        migrations.AddField(
            model_name='nombreelemento',
            name='requiere_numero',
            field=models.BooleanField(default=False, help_text='Número de linea telefonica Para celulares y SIM', verbose_name='Requiere Número'),
        ),
        migrations.AddField(
            model_name='nombreelemento',
            name='requiere_operador',
            field=models.BooleanField(default=False, help_text='Ej: Claro, Movistar (para celulares y SIM)', verbose_name='Requiere Operador'),
        ),
        migrations.AddField(
            model_name='nombreelemento',
            name='requiere_puertos',
            field=models.BooleanField(default=False, help_text='Ej: USB-A, HDMI, RJ45 (Para Swiches, routers,etc)', verbose_name='Requiere puerto'),
        ),
        migrations.AddField(
            model_name='nombreelemento',
            name='requiere_tipo',
            field=models.BooleanField(default=False, help_text='Ej: inalambrico, De cocina, de oficina ', verbose_name='Requiere Tipo'),
        ),
    ]
