# Generated by Django 4.2.26 on 2026-02-27 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfilusuario_tipo_usuario'),
        ('inventario', '0012_elemento_nombre_elemento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='bodega_destino',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='bodega_origen',
        ),
        migrations.AlterField(
            model_name='elemento',
            name='bodega_actual',
            field=models.ForeignKey(help_text='Usuario con rol de bodega donde se encuentra actualmente el elemento', limit_choices_to={'rol__nombre': 'Bodega'}, on_delete=django.db.models.deletion.PROTECT, related_name='elementos_en_bodega', to='usuarios.perfilusuario', verbose_name='Bodega Actual'),
        ),
        migrations.DeleteModel(
            name='Bodega',
        ),
    ]
