# Generated by Django 4.2.26 on 2026-03-26 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_perfilusuario_puede_autorizar'),
        ('inventario', '0016_movimientoinventario_firma_autoriza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='usuario_autoriza',
            field=models.ForeignKey(blank=True, help_text='Usuario que autoriza el movimiento', limit_choices_to={'perfil__puede_autoriza': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_autorizados', to='usuarios.perfilusuario', verbose_name='Autorizado por'),
        ),
    ]
