# Generated by Django 4.2.26 on 2026-04-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_nombreelemento_requiere_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='tipo_cuenta',
            field=models.CharField(blank=True, choices=[('Principak', 'Principal'), ('Subcuenta', 'Subcuenta')], max_length=20, null=True, verbose_name='Tipo de Cuenta'),
        ),
    ]
