# Generated by Django 4.2.26 on 2026-04-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0022_elemento_tipo_cuenta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientoinventario',
            old_name='firmado_completamente',
            new_name='es_firmado_total',
        ),
        migrations.AlterField(
            model_name='elemento',
            name='tipo_cuenta',
            field=models.CharField(blank=True, choices=[('Principal', 'Principal'), ('Subcuenta', 'Subcuenta')], max_length=20, null=True, verbose_name='Tipo de Cuenta'),
        ),
    ]
