# Generated by Django 4.2.26 on 2026-05-27 14:21

import apps.inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0026_remove_movimientoinventario_firma_autoriza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='firma_autoriza',
            field=models.ImageField(blank=True, null=True, upload_to=apps.inventario.models.ruta_firmas, verbose_name='Firma Autoriza'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='firma_elabora',
            field=models.ImageField(blank=True, null=True, upload_to=apps.inventario.models.ruta_firmas, verbose_name='Firma Elabora'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='firma_recibe',
            field=models.ImageField(blank=True, null=True, upload_to=apps.inventario.models.ruta_firmas, verbose_name='Firma Recibe'),
        ),
    ]
